# Generated by Django 5.0.3 on 2024-03-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='headline',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
